# permissions for end users to edit websites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: website-editor-role
rules:
- apiGroups:
  - website.xianyuluo.com
  resources:
  - websites
  - deployment
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - website.xianyuluo.com
  resources:
  - websites/status
  verbs:
  - get
